# Generated by Django 4.0.3 on 2022-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='complete',
        ),
        migrations.AddField(
            model_name='match',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
