# Generated by Django 4.0.3 on 2022-05-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_game_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-datetime_played']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-datetime_started']},
        ),
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ['match']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['match']},
        ),
    ]
