# Generated by Django 4.0.3 on 2022-08-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_game_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='match',
            name='created_by',
        ),
    ]
