# Generated by Django 4.1.1 on 2022-09-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_game_created_by_remove_match_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_points_cache',
            field=models.IntegerField(default=0),
        ),
    ]
